name: Update Stock Data

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install tushare

      - name: Run stock data script
        run: |
          python get_stock_data.py

      - name: Commit and push updated stock data
        run: |
          git config --local user.email "you@example.com"  # 替换为你的邮箱
          git config --local user.name "GitHub Actions"
          git add stock_data.json  # 将 JSON 文件添加到 Git
          git commit -m "Update stock data"
          git push origin main
